stages:
   - build
   - test
   - deploy

build_job:
 stage: build
 script:
   - docker build . -t node-app:latest
 tags:
   - dev

test_job:   
  stage: test
  script:
    - echo "TESTING"
  tags:
    - dev

deploy_job:
 stage: deploy
 script:
   - docker compose down
   - docker compose up -d
 tags: 
   - dev
